version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: prodesp_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: prodesp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: prodesp_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # Painel de administração do RabbitMQ
      - "15674:15674" # Porta do Web STOMP
    networks:
      - prodesp_network
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_web_stomp &&
             rabbitmq-server"

volumes:
  postgres_data:
    driver: local

networks:
  prodesp_network:
    driver: bridge
